version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CRC"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9t5y8kzxrcfj"
s3_prefix = "CRC"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
